### ISSUE TITLE
Final Project Proposal

### ISSUE THREAD

**Issue by JuKyoKim** [JuKyoKim/SpooderDeadLonks#1]
# title: DeadLink Checker!
## summary:

checking for dead links on web apps for manual QA, Legal, and Product team takes a long time since it requires them to actively click on each link looking for a response.

MY idea is to create a single page application that will just require a base url(homepage)
and it will hit everylink on that page plus the nested links on everypage hit(recursively).

It will incorporate technologies such as phantom and casper js, maybe selenium (for a more UI validating type automation test scripts).

it will use angular to have some kind of visualization that will display the results of each link hit.
## MVP of features:
- check for deadlink and return results
## Expansion(in the future):
- incorporate a more ui based automation with selenium
- allow users to submit a simple JSON file or a feature file(cucumber) to run a basic cause and effect automation validation.(ex - given user is on homepage | when user clicks on sign in | then the overlay appears)

**Comment by jasonseminara** [comment]
This looks promising. I'm concerned about the limited functionality of the website. I totally understand the idea of spidering a site for dead links, but what more value are you adding with this website? Can you provide some user stories describing a logged-in user's interaction?

**Comment by JuKyoKim** [comment]
User Stories
As a Manual QA analyst:
- I want to have a web app tool that allows me to scour the target web application for any deadlinks. without the need to install 3rd party applications(eliminates the cross platform problems no more WINE!)
- I want to see the status code and url for each link hit
- I want to see that how long it took to load the page
- I want to see that it only hits URLS with the BASE URL, any external links or embeds will be ignored
- I want to generate a report (json file) that i can download for usage(could be for other automation scripts or something idk....)

I might modify the deadlinks part of this application and switch it up for any HTML tags, so its more "dynamic" (so its going to check for deadlinks along with w.e HTML tag user specified)

This might still be "limited" so i'll try to think of better stories, or a new app altogether. @jasonseminara

**Comment by jasonseminara** [comment]
Dont change course this late in the game, unless you have some serious reason or emergency. I think you have enough to go forward. Approved.
